<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
        <OutputPath>bin\Release\MapAdvertisements\</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <DebugType>none</DebugType>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CounterStrikeSharp.API" Version="1.0.363" />
      <None Update="lang\**\*.*" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="MenuManagerApi"><HintPath>MenuManagerApi.dll</HintPath></Reference>
    </ItemGroup>

</Project>